name: Basic CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -al /home/Practice_YAML/
      
      - name: set up Node.js
        uses: actions/setup-node@v2
        with :
          node-version: '14'

      - name: Install dependencies
        run: cd /home && npm install

      - name: Run tests
        run: cd /home && npm test

